### ISSUE TITLE
Add a `BasemapSelection` component to allow the user to change the map style

### ISSUE THREAD

**Issue by rudokemper** [ConservationMetrics/guardianconnector-views#51]
## Feature Request

Recently, we have established that we would like to add an option for users to explore their change detection alerts overlaid on various satellite imagery - e.g. Planet (cf. https://github.com/ConservationMetrics/guardianconnector-views/issues/44), Sentinel - backgrounds. To do this, we will need a basemap picker to change the map style as per [this Mapbox API example](https://docs.mapbox.com/mapbox-gl-js/example/setstyle/).

Initial options may include: default Mapbox map, `satellite-streets-v12` and Planet NICFI.

### Implementation plan

- [x] Let's create a new component called `BasemapSelector` which provides a UI to toggle between different basemap options. 
- [x] The component should indicate the basemap that is currently selected.
- [x] When a new basemap is selected, the component should emit a new style URL (or stylesheet definition) upstream to the parent component.
- [x] The `Map` and `AlertsDashboard` components should listen for changes in the active style URL, and repaint the map when a new style is set.
  - [x] In so doing, all of the alerts should persist to the new map style.
- [x] An option to toggle Planet NICFI should only be shown if a VIEWS_CONFIG variable `PLANET_API_KEY` is set. 
- [x] As an initial acceptance criteria for Planet NICFI, let's load the latest monthly basemap. Follow-on work in https://github.com/ConservationMetrics/guardianconnector-views/issues/44 can then add a slider to select a specific month & year for Planet.

### Inspo

Global Forest Watch:
![image](https://github.com/ConservationMetrics/guardianconnector-views/assets/31662219/d802182f-20d9-47da-9cc1-40d6c0e72c80)

Explorer.Land:
![image](https://github.com/ConservationMetrics/guardianconnector-views/assets/31662219/bda075c3-0fa2-4de8-8321-a38b1f3ddb23)

Esri:
![image](https://github.com/ConservationMetrics/guardianconnector-views/assets/31662219/809e44e0-88ce-418c-9845-562d5726345c)
